import React, { Component } from 'react'

export class Footer extends Component {
  render() {
    return (
      <div> 
        <p> All data are generated by LT600 Pro device. </p> 
      </div>
    )
  }
}

export default Footer