import React, { Component } from 'react'
import  './style.css'
export class Footer extends Component {
  render() {
    return (
      <div className='footer'> 
        <p className='footer-text'> All data are generated by LT600 Pro device. </p> 
      </div>
    )
  }
}

export default Footer